steps:
  # 1. Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/workspace-mila-repo/workspace-mila', '-f', 'backend/Dockerfile', './backend']

  # 2. Push da imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/workspace-mila-repo/workspace-mila']

  # 3. Deploy para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'workspace-mila'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/workspace-mila-repo/workspace-mila'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=whatsapp-bot-mila,FIRESTORE_DB_ID=db-clientes-contcertbr'