steps:
  # 1. Build da imagem Docker usando o contexto da pasta backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/workspace-mila', './backend']

  # 2. Push da imagem
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workspace-mila']

  # 3. Deploy para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'workspace-mila'
      - '--image'
      - 'gcr.io/$PROJECT_ID/workspace-mila'
      - '--region'
      - 'southamerica-east1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=whatsapp-bot-mila,FIRESTORE_DB_ID=db-clientes-contcertbr'

      options:
  logging: CLOUD_LOGGING_ONLY
  # Adicione esta linha abaixo para garantir que ele use o comportamento regional
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
